name = "planner"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "planner"
database_id = "b1ede3f4-a7f4-44a7-9b06-9d53f3ac9e31"
migrations_dir = "migrations"
